@echo off
cd /d %~dp0\..

echo Starting all event listeners...

echo Starting OrderCreateRequestedEvent listener...
start cmd /k "php consumer.php OrderCreateRequestedEvent"
echo Starting OrderCreatedEvent listener...
start cmd /k "php consumer.php OrderCreatedEvent"
echo Starting InventoryDeductedEvent listener...
start cmd /k "php consumer.php InventoryDeductedEvent"
echo Starting PaymentProcessedEvent listener...
start cmd /k "php consumer.php PaymentProcessedEvent"
echo Starting RollbackInventoryEvent listener...
start cmd /k "php consumer.php RollbackInventoryEvent"
echo Starting RollbackOrderEvent listener...
start cmd /k "php consumer.php RollbackOrderEvent"

echo All listeners started
pause
